webtalk_init -webtalk_dir C:/Users/alceu/Documents/Doutorado/2dof_esc_pole_ila/Fishhook_test/Fishhook_test.sim/sim_1/behav/xsim/xsim.dir/Fishhook_test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 27 23:43:49 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a9cb6be5-6586-4e7b-a407-16cc44b05203" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c16e0686d64546a8b1bb714fd3f11493" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12792_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3643716730 -regid "" -xml C:/Users/alceu/Documents/Doutorado/2dof_esc_pole_ila/Fishhook_test/Fishhook_test.sim/sim_1/behav/xsim/xsim.dir/Fishhook_test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/alceu/Documents/Doutorado/2dof_esc_pole_ila/Fishhook_test/Fishhook_test.sim/sim_1/behav/xsim/xsim.dir/Fishhook_test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/alceu/Documents/Doutorado/2dof_esc_pole_ila/Fishhook_test/Fishhook_test.sim/sim_1/behav/xsim/xsim.dir/Fishhook_test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
